services:

  client:
    build: ./frontend
    depends_on:
      - employee
    ports:
      - "3000:3000"

  employee:
    build: ./employeeservice
    ports: 
      - "5003:5003"
    environment:
      MONGODB_URI: mongodb://myUser:myPassword@mongo:27017/kindergarten?authSource=admin
      DATABASE_NAME: kindergarten
    depends_on:
      - mongo

  student:
    build: ./studentservice
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: mongodb://myUser:myPassword@mongo:27017/kindergarten?authSource=admin
      DATABASE_NAME: kindergarten
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUser
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_DATABASE: kindergarten
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: