services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUser
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_DATABASE: kindergarten
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: