services:

  nginx:
    build: ./nginx
    restart: always
    depends_on: 
      - client
      - employee
      - student
      - teacher
    ports:
      - "80:80"
    
  client:
    build: ./frontend
    depends_on:
      - employee
      - student
      - teacher


  employee:
    build: ./employeeservice

    environment:
      MONGODB_URI: mongodb://myUser:myPassword@mongo:27017/kindergarten?authSource=admin
      DATABASE_NAME: kindergarten
    depends_on:
      - mongo

  student:
    build: ./studentservice

    environment:
      MONGODB_URI: mongodb://myUser:myPassword@mongo:27017/kindergarten?authSource=admin
      DATABASE_NAME: kindergarten
    depends_on:
      - mongo

  teacher:
    build: ./teacherservice

    environment:
      MONGODB_URI: mongodb://myUser:myPassword@mongo:27017/kindergarten?authSource=admin
      DATABASE_NAME: kindergarten
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUser
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_DATABASE: kindergarten
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: