apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-deployment
spec:
  selector:
    matchLabels:
      app: teacher
  template:
    metadata:
      labels:
        app: teacher
    spec:

      volumes:
        - name: access-log-volume
          persistentVolumeClaim:
            claimName: backend-log-persistance

      containers:
      - name: teacher
        image: sabirsaheel0/school-app-teacher:0.1
        ports:
        - containerPort: 5002
        volumeMounts:
        - mountPath: /app/logs
          name: access-log-volume 
        env:

        - name: MONGO_USER 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        
        - name: MONGO_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password

        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config 
              key: MONGODB_HOST

        - name: MONGO_PORT 
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGODB_PORT
        
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: DATABASE_NAME

        - name: MONGODB_URI
          value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(DATABASE_NAME)?authSource=admin"

      
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-clusterip
spec:
  selector:
    app: teacher
  ports:
  - port: 5002
    targetPort: 5002