upstream frontend{
    server client:3000;
}

upstream student-service{
    server student:5001;
}

upstream teacher-service{
    server teacher:5002;
}

upstream employee-service{
    server employee:5003;
}

server{
    listen 80;

    location / {
        proxy_pass http://frontend;
    }
    location /student-svc/{
        rewrite /student-svc/(.*) /$1 break;
        proxy_pass http://student-service;
    }
    location /teacher-svc/{
        rewrite /teacher-svc/(.*) /$1 break;
        proxy_pass http://teacher-service;
    }
    location /employee-svc/{
        rewrite /employee-svc/(.*) /$1 break;
        proxy_pass http://employee-service;
    }
}